cd ../../T2VRec/
# ------------------------------------------------dense_all_action_plus
python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus/1 --model=dense_all_action_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=1
python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus/2 --model=dense_all_action_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=2
python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus/3 --model=dense_all_action_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=3
python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus/4 --model=dense_all_action_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=4
python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus/5 --model=dense_all_action_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=5

# ------------------------------------------------dense_all_action_plus_plus
#python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus_plus/1 --model=dense_all_action_plus_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=1
#python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus_plus/2 --model=dense_all_action_plus_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=2
#python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus_plus/3 --model=dense_all_action_plus_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=3
#python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus_plus/4 --model=dense_all_action_plus_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=4
#python main.py --dataset=ml-20m --log_dir=F_experiments/T/ml-20m/Scratch/sampled_softmax/lr=0.001/t2v_dense_all_action_plus_plus/5 --model=dense_all_action_plus_plus --device=cuda --loss_function=sampled_softmax --eval_epoch=5 --num_epochs=1000 --temporal=true --lr=0.001 --maxlen=200 --k_fold=5